#include <stdio.h>

#define TARGET 4000000

int main() {

  int fib0 = 1;
  int fib1 = 2;

  int sum = 0;
  while(fib1 < TARGET) {
    if(fib1 %2 == 0) { sum += fib1; }
    int t = fib0;
    fib0 = fib1;
    fib1 += t;
  }

  printf("Sum of even fib numbers < %d = %d", TARGET, sum);
}

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/
